import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Some Like It Hot",
  description: "Generated by create next app",
};

function Footer() {
  return (
        <footer>
            <p>Thank you for visiting our site!</p>
            <p>Send us a message: <a href="mailto:fredoniasomelikeithot@gmail.com">fredoniasomelikeithot@gmail.com</a></p>
        </footer>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
